### ISSUE TITLE
Site para aprender 1000 palavras básicas

### ISSUE THREAD

**Issue by thgfrnk** [gbdsantos/guia-estudo-japones#1]
_https://en.wiktionary.org/wiki/Appendix:1000_Japanese_basic_words_

Foi muito útil para mim quando comecei a estudar. Espero que ajude os novos gafanhotos.

**Comment by gbdsantos** [comment]
Caraca tem um tempão que foi aberta essa issue, foi mal!
Eu não vi nenhuma notificação, vou adicionar no repo :blush:

Adicionei lá, na sessão de websites :v:
